# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='noti_type',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Full notification'), (2, b'Web only notification'), (3, b'Email only notification')], default=1),
        ),
    ]
